- name: "Sonarqube install prerequisites"
  hosts: sonarqubeservers
  #TODO: manage centos
  tasks:
    - include: tasks/install_prerequisites.yaml


- name: "Sonarqube configure system"
  hosts: sonarqubeservers

  tasks:
    - include: tasks/configure_operating_system.yaml


- name: "Install Sonarqube Server"
  hosts: sonarqubeservers
  vars:
    remote_download_dir: "/tmp/sonarDownloadDir"
    remote_archive_file_path: "{{ remote_download_dir }}/sonar.zip"
  tasks:
    - include: tasks/download_and_install_sonar.yaml


- name: Prepare conf dir and extentions dir
  hosts: sonarqubeservers
  tasks:
    - include: tasks/prepare_conf_and_extensions_dir.yaml

- name: Configure sonar
  hosts: sonarqubeservers
  tasks:
    - include: tasks/configure_sonar.yaml

- name: Configure Systemd
  hosts: sonarqubeservers
  tasks:
    - include: tasks/create_service.yaml