- name: "Upgrade system file descriptors and memory limit"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: "fs.file-max", value: "100000" }
    - { name: "vm.max_map_count", value: "2621440" }

- name: "Upgrade file limits"
  pam_limits:
    domain: '*'
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - { limit_type: "soft", limit_item: "nproc", value: "65535" }
    - { limit_type: "hard", limit_item: "nproc", value: "65535" }
    - { limit_type: "soft", limit_item: "nofile", value: "65535" }
    - { limit_type: "hard", limit_item: "nproc", value: "65535" }

#TODO: reboot if file is changed
- name: "Configure SECCOMP"
  lineinfile:
    path: "/boot/config-{{ ansible_kernel }}"
    regexp: '^CONFIG_HAVE_ARCH_SECCOMP_FILTER='
    line: "CONFIG_HAVE_ARCH_SECCOMP_FILTER=y"

- name: "Configure SECCOMP"
  lineinfile:
    path: "/boot/config-{{ ansible_kernel }}"
    regexp: '^CONFIG_SECCOMP_FILTER='
    line: "CONFIG_SECCOMP_FILTER=y"

- name: "Configure SECCOMP"
  lineinfile:
    path: "/boot/config-{{ ansible_kernel }}"
    regexp: '^CONFIG_SECCOMP='
    line: "CONFIG_SECCOMP=y"